function B = Bfcn(t1,t2)
%Bfcn
%    B = Bfcn(T1,T2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    15-May-2024 02:45:34

t3 = cos(t2);
t4 = t3.*4.183051653e-3;
t5 = t4+3.86841468610732e-3;
B = reshape([t3.*8.366103306e-3+1.296029878973884e-2,t5,t5,3.86841468610732e-3],[2,2]);
end
