function B = Bfcn(t1,t2)
%Bfcn
%    B = Bfcn(T1,T2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    15-Jun-2024 17:00:57

t3 = cos(t2);
t4 = t3.*5.97310296e-3;
t5 = t4+4.558903792190174e-3;
mt1 = [t3.*1.194620592e-2+1.71795253067423e-2,t5,t5];
mt2 = [8.772449086163049e-3];
B = reshape([mt1,mt2],2,2);
end
