function C = Cfcn(t1,t2,t1d,t2d)
%Cfcn
%    C = Cfcn(T1,T2,T1D,T2D)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    15-Jun-2024 17:00:58

t3 = sin(t2);
t4 = t3.*t1d.*5.97310296e-3;
t5 = t3.*t2d.*5.97310296e-3;
t6 = -t5;
C = reshape([t6,t4,-t4+t6,0.0],[2,2]);
end
